package com.trackflow.entity;

import jakarta.persistence.*;
import lombok.*;

/**
 * User entity representing a registered user in TrackFlow.
 *
 * <p>This is the central entity of the application. Almost every other entity
 * has a relationship with User (reporter, assignee, commenter, etc.).</p>
 *
 * <h3>Design Decisions:</h3>
 * <ul>
 *   <li><strong>Email as unique identifier:</strong> Users log in with email, not username.
 *       This is standard in modern SaaS applications.</li>
 *   <li><strong>Password stored as hash:</strong> We never store plaintext passwords.
 *       BCrypt generates a 60-character hash that includes the salt.</li>
 *   <li><strong>Profile image path, not blob:</strong> Storing images in the database
 *       is an anti-pattern. We store the file path/URL and use StorageService
 *       to retrieve the actual file.</li>
 *   <li><strong>@Table(name = "users"):</strong> "user" is a reserved keyword in PostgreSQL.
 *       Always name your table "users" (plural) to avoid SQL errors.</li>
 * </ul>
 *
 * <h3>Interview Question:</h3>
 * <p>"Why not store images as BLOBs in the database?"</p>
 * <p>Answer: BLOBs increase database size dramatically, slow down queries,
 * make backups larger, and can't leverage CDN caching. Store files in
 * object storage (S3/MinIO) and keep only the reference path in the DB.</p>
 */
@Entity
@Table(name = "users", indexes = {
        @Index(name = "idx_user_email", columnList = "email", unique = true),
        @Index(name = "idx_user_organization", columnList = "organization_id")
})
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class User extends BaseEntity {

    /**
     * Primary key — auto-generated by the database.
     *
     * <p>{@code GenerationType.IDENTITY} uses PostgreSQL's SERIAL/BIGSERIAL
     * auto-increment. This is preferred over SEQUENCE for simplicity
     * and over TABLE for performance.</p>
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * User's full name.
     */
    @Column(name = "full_name", nullable = false, length = 100)
    private String fullName;

    /**
     * Email address — used as the login identifier.
     *
     * <p>{@code unique = true} creates a database-level unique constraint,
     * preventing duplicate emails even if application-level validation
     * is bypassed.</p>
     */
    @Column(nullable = false, unique = true, length = 150)
    private String email;

    /**
     * BCrypt-hashed password.
     *
     * <p>BCrypt hashes are always 60 characters long.
     * We set length to 100 for safety margin.</p>
     */
    @Column(nullable = false, length = 100)
    private String password;

    /**
     * Path to the user's profile image.
     * Stored as a relative path; actual file is in StorageService.
     */
    @Column(name = "profile_image")
    private String profileImage;

    /**
     * User's role in the system.
     *
     * <p>{@code EnumType.STRING} stores the role name as text ("DEVELOPER"),
     * not as an index number. This is safer against enum reordering.</p>
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 30)
    private Role role;

    /**
     * Whether the user's account is active.
     *
     * <p>Inactive users cannot log in. This is different from soft delete —
     * an admin can deactivate a user temporarily without deleting them.</p>
     */
    @Column(nullable = false, columnDefinition = "boolean default true")
    private boolean active = true;

    /**
     * Whether the user's email has been verified.
     */
    @Column(name = "email_verified", nullable = false, columnDefinition = "boolean default false")
    private boolean emailVerified = false;

    /**
     * The organization this user belongs to.
     *
     * <p>{@code @ManyToOne} = Many users belong to one organization.
     * {@code FetchType.LAZY} = Don't load the organization unless explicitly accessed.
     * This prevents the N+1 query problem.</p>
     *
     * <h3>Interview Question:</h3>
     * <p>"What is the N+1 query problem?"</p>
     * <p>Answer: If you load 100 users with EAGER fetch on organization,
     * JPA fires 1 query for users + 100 queries for each user's organization = 101 queries.
     * With LAZY, the organization is loaded only when you call user.getOrganization(),
     * and you can use JOIN FETCH to load it in a single query when needed.</p>
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "organization_id")
    private Organization organization;
}
